# Generated by Django 5.2.15 on 2026-07-01 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('pcap_file', models.CharField(max_length=255)),
                ('challenge_question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('resources', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('ai_explanation', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_number', models.IntegerField()),
                ('source_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(max_length=20)),
                ('flags', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='core.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labs_completed', models.IntegerField(default=0)),
                ('total_labs', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
