# Generated by Django 5.2.15 on 2026-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='pcap_file',
            field=models.FileField(upload_to='pcaps/'),
        ),
    ]
