# Generated by Django 5.2.15 on 2026-07-04 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lab_pcap_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='challenge_question',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='correct_answer',
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.lab')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.challenge'),
            preserve_default=False,
        ),
    ]
