# Generated by Django 5.2.15 on 2026-07-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_attempt_lab_remove_lab_challenge_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packets', to='core.challenge'),
        ),
    ]
